import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { AuthProvider } from "@/utils/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10 px-20">
            <NavbarComponent></NavbarComponent>
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
